### ISSUE TITLE
formsnap.dev is down

### ISSUE THREAD

**Issue by WillDelish** [svecosystem/formsnap#172]
### Change Type

Correction

### Proposed Changes

Just informing that formsnap.dev is not showing an SSL cert and giving a 403 forbidden error.

Looks the IP A records are pointed to a private address
formsnap.dev.		0	IN	A	192.73.240.25
formsnap.dev.		0	IN	A	192.73.240.22

**Comment by huntabyte** [comment]
Is this still happening? I'm not seeing it on my end.

**Comment by WillDelish** [comment]
Its all good on my end! There's a chance the DNS of the network I was on was having issues or it was a rare outage.
