### ISSUE TITLE
Preserve form state when moving between pages

### ISSUE THREAD

**Issue by Sourabhpatel1** [svecosystem/formsnap#190]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

in the method prescribed in the documentation the formData is a writable store but the values are lost whenever the load function runs on navgation. I would like a way to preserve a form state on navigation to another page and back. for example there is a page to add product and another page to add a category when a user fills out the form to add product partially and navigates to the add category page the partially filled state of add product form is lost. 

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
This would be an enhancement for sveltekit-superforms, not formsnap. You can look into snapshots to see if that's what you are looking to do.
