### ISSUE TITLE
Add a <Form.FormErrors /> component

### ISSUE THREAD

**Issue by bfovez** [svecosystem/formsnap#193]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Add a `<Form.FormErrors />` which would behave exactly as `<Form.FieldErrors />` but would deal with the 'global form errors', that is the ones from `form.errors._errors` instead of `form.errors.<field name here>`.

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
https://github.com/svecosystem/formsnap/discussions/158
